### ISSUE TITLE
After rebooting the ec2 instance doesn't work anymore

### ISSUE THREAD

**Issue by zazoomauro** [webdigi/AWS-VPN-Server-Setup#10]
After rebooting the ec2 instance connects fine to the VPN but the client doesn't have internet access anymore.

**Comment by webdigi** [comment]
are you sure you have not changed any other setting? also why did you have to restart the instance?

**Comment by zazoomauro** [comment]
100% sure
My test was create the cloudfront VPN. VPN Connection fine and internet client fine
Reboot the VPN ec2 instance. VPN Connection fine and not client internet

**Comment by zazoomauro** [comment]
@webdigi I restarted the instance by mistake...

**Comment by webdigi** [comment]
ok. not sure why a restart causes issues. please try another instance if possible and confirm if it works.

**Comment by zazoomauro** [comment]
I have a new one and is working fine without rebooting it 😉

**Comment by chhantyal** [comment]
That's because EC2 public IP might change when you reboot server. @webdigi What about adding option to attach Elastic IP just after instance is created and use that IP? This way, reboot issue could be solved.

**Comment by webdigi** [comment]
See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-reboot.html

"When you reboot an instance, it remains on the same physical host, so your instance keeps its public DNS name, private IP address, and any data on its instance store volumes." It should keep the same DNS name and public IP.

Adding elastic IP would increase cost & add additional fields in the configuration. Most users shut down and create new VPN as that is easier.
