### ISSUE TITLE
How to achieve multi-users?

### ISSUE THREAD

**Issue by nick198205** [webdigi/AWS-VPN-Server-Setup#11]
I want to konw how to achieve multi-users on AWS-VPN-Server using this method?  
Thanks!

**Comment by kitzy** [comment]
I would also like to know how to add a 2nd user.

**Comment by webdigi** [comment]
it is totally possible to add multiple users. We did not want to make the interface complicated for beginners. Please edit the cloud formation template. Pull requests are welcome.
