### ISSUE TITLE
Server stops responding after a day or so

### ISSUE THREAD

**Issue by kitzy** [webdigi/AWS-VPN-Server-Setup#13]
I've been using this setup for a few months without incident, however over the last few days I've run into a situation where I have to rebuild the server every 24 hours or so. I haven't made any changes to the server, it just stops responding and the only thing that seems to work is blowing the server away and rebuilding from scratch. Any idea as to why this might be?

"The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator."

**Comment by webdigi** [comment]
A few questions
- Have you made any changes to your VPC? 
- Is the EC2 instance still running?

Another solution is to try another region and run the same operation.

**Comment by kitzy** [comment]
I haven't made any changes to the VPC, aside from assigning an Elastic IP to the instance. I've verified the behavior is the same when I disassociate the Elastic IP and use the standard public IP.

The EC2 instance is still running. Rebooting the instance doesn't seem to help.

**Comment by webdigi** [comment]
Did you also try another region?

**Comment by michaelreinhart** [comment]
I'm seeing this behaviour too.

**Comment by michaelreinhart** [comment]
Curiously, I can connect to the VPN instance using PPTP.

**Comment by kitzy** [comment]
I believe this was environmental due to a poor internet connection where I was traveling. Since returning to the US it has been rock solid.

**Comment by chhantyal** [comment]
I think this is valid issue. After attaching Elastic IP, I can connect to VPN but doesn't  work.
