### ISSUE TITLE
Cannot deploy template in Mumbai (ap-south)

### ISSUE THREAD

**Issue by navneetkarnani** [webdigi/AWS-VPN-Server-Setup#15]
I tried deploying the template to Mumbai, but that failed. 

Error:

Template validation error: Template error: Unable to get mapping for AWSRegionArch2AMI::ap-south-1::HVM64

**Comment by webdigi** [comment]
Can you please confirm what server size did you select? Are any other server sizes working?

Mumbai is a new region and probably have different mapping code.

**Comment by navneetkarnani** [comment]
Same as mentioned in the article, Standard.Free.

**Comment by jainendra** [comment]
Same here.. not working

**Comment by MRrnumber** [comment]
Hey download this file and upload manually and it work, I have added the new aws ap-south-1 address in the list.
[Unified-Cloud-Formation.json.zip](https://github.com/webdigi/AWS-VPN-Server-Setup/files/932015/Unified-Cloud-Formation.json.zip)

**Comment by webdigi** [comment]
@MRrnumber - thanks, the AMI is updated in https://s3.amazonaws.com/webdigi/VPN/Unified-Cloud-Formation.json 

Please check the latest version.

**Comment by webdigi** [comment]
We have a major update to the VPN server code and this should improve stability significantly. I look forward to your tests on the new system 333b293

Please do follow instructions https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/ or video https://www.youtube.com/watch?v=fBBERp5CUgo and let us know if you have any trouble with the new system.

@MRrnumber @jainendra @navneetkarnani - Please do try the latest server and it should be much more stable now.
