### ISSUE TITLE
PPTP Server fails to connect with DD-WRT router VPN client

### ISSUE THREAD

**Issue by bebblebrox** [webdigi/AWS-VPN-Server-Setup#16]
I have setup the VPN server as detailed. I have been able to connect with both ios devices and my win 10 PC, but I have failed miserably with the router VPN client. 

At the heart of the issue is both the ios devices and Win 10 effectively dynamically "handshake" with the server but the DD-WRT router requires the exact parameters (and I couldn't find them anywhere). I have looked at the template you provided (thank you) but there are a number of settings I am unsure of: 

![vpn](https://cloud.githubusercontent.com/assets/21189338/17881264/5ba5b8ee-6947-11e6-8294-57626ada7682.png)

As you can see with the attached image I know : 
1. the server IP. 
2. Looking at the template I assume the Remote Subnet is the server IP of 10.0.0.1 but not sure, with the Remote Subnet Mask 255.255.255.255 (but the client will not allow me to save this config)
3. Unsure whether I need to insist on mppe. (I can see when my win10 client connects its at MPPE 128. So, while I have items inthe MPPE Encryption box, unsure if I should and have tried with and without.
4. MTU in the template is 1280
5. MRU in the template is 1280
6. Assume I need to enable NAT (although not sure)
7. I know my username and pwd
8. Additional PPTP options: not sure?

Any help you can give me in filling in the details would be great. Many thanks

**Comment by arabold** [comment]
I've finally managed to get my setup working with a Linksys E2500 and Tomato after several hours of trial-and-error. The trick was a missing `require-mppe-128` in the additional options field. Hope this helps you, too.
