### ISSUE TITLE
Problem connecting a TL-WR941ND router

### ISSUE THREAD

**Issue by MickeyKimhi** [webdigi/AWS-VPN-Server-Setup#17]
Hello
I managed to create the instance quickly as well as connecting to it form windows. 
I also tried it from my Android device and it connects. Please note that once connected the internet is not accessible. Looking at the IP config I see that the gateway is set to 0.0.0.0.

When choosing PPTP on my router and providing the same user/psw it does NOT connect.

Any idea what could be the issue? Could it be related to the IPSEC? There is no place to provide it in my router setting.

Thanks,
Mickey.

**Comment by webdigi** [comment]
Did you manage to sort it out? Please reopen if this was not a problem with the specific router. You can add docs for setup on routers here https://github.com/webdigi/AWS-VPN-Server-Setup/tree/master/docs
