### ISSUE TITLE
Add ap-south-1 ami id

### ISSUE THREAD

**Issue by dbjpanda** [webdigi/AWS-VPN-Server-Setup#19]

**Comment by webdigi** [comment]
Added to https://github.com/webdigi/AWS-VPN-Server-Setup/commit/56baa714c8cbca18456c894e1046cf2962cfe352

Please use the updated the same production JSON https://s3.amazonaws.com/webdigi/VPN/Unified-Cloud-Formation.json

Please reopen if it does not work for you in the new Mumbai region
