### ISSUE TITLE
Cannot connect or ping server

### ISSUE THREAD

**Issue by ajlee** [webdigi/AWS-VPN-Server-Setup#2]
Hi thanks for the tutorial. I go through the steps exactly as described but cannot connect to the VPN. I also tried pinging it and got no response. Do you know how I can fix this?

**Comment by webdigi** [comment]
Ping is turned off by default. Did you see any error while creating the stack?

**Comment by ajlee** [comment]
No error. However, I just tried deleting it and creating it under a different region and it works fine. Strange! Thanks :)

**Comment by webdigi** [comment]
Thanks for letting us know. It might take a minute or two after the stack complete status for the VPN to start functioning. Let us know if you still have a problem with any region.

**Comment by mobitar** [comment]
Same issue. Created one with Oregon region and it did not work. Then created one in N. California region and it worked.
