### ISSUE TITLE
Why it is showing time out? Unable to connect vpn 

### ISSUE THREAD

**Issue by dbjpanda** [webdigi/AWS-VPN-Server-Setup#22]

**Comment by webdigi** [comment]
did you wait for about 5 minutes after starting? the output might show the ip but it is still installing the software in the background

**Comment by dbjpanda** [comment]
________________________________

**Comment by dbjpanda** [comment]
Yes its still showing time out after 3 hours.

________________________________

**Comment by webdigi** [comment]
what region was it?

**Comment by dbjpanda** [comment]
ap-south-1 mumbai

________________________________

**Comment by webdigi** [comment]
please try again if possible by creating a new stack.

**Comment by jainendra** [comment]
@dbjpanda how did you solve it? Did it work?

**Comment by dbjpanda** [comment]
@jainendra Yes it has been updated by webdigi. ap-south-1 has been added. You can try it now.
