### ISSUE TITLE
mac os x sierra connection error

### ISSUE THREAD

**Issue by fishhelper** [webdigi/AWS-VPN-Server-Setup#24]
Hi,

My mac, running macOS 10.12.1, is unable to connect to the vpn server. "The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your administrator."

How can I debug this connectivity matter? I attempted to create a stack in two different regions and experienced the same connectivity rejection. The default VPC NACL permits inbound and outbound. What else should be verified in the aws console?

PPTP is not an option with the latest version of macOS.

Thx

<img width="420" alt="screen shot 2016-12-08 at 11 07 11 pm" src="https://cloud.githubusercontent.com/assets/18660465/21037344/17a50b74-bd9b-11e6-9ab1-4c2e5ab6cb98.png">

**Comment by outsideris** [comment]
I have same issue.

**Comment by ShanghaiTheBrad** [comment]
Same issue with my iPhone

**Comment by janyk** [comment]
Same issue here, maybe need to update the tutorial to allow for connections over ipsec?

**Comment by webdigi** [comment]
Please wait 5-10 minutes after initial setup to allow server setup to be complete. This is after receiving the IP address on cloud formation outputs tab.

**Comment by qqinzheng** [comment]
i have  same issue with  my Mac.
i have changed  4 regions ,but still not respond.
