### ISSUE TITLE
Invalid Mapping For London Region

### ISSUE THREAD

**Issue by samdxb** [webdigi/AWS-VPN-Server-Setup#25]
Hi, Is there a way to set up this VPN in London region? 

Thank you very much.
Sampath

**Comment by pReya** [comment]
I'd really appreciate this, too.

**Comment by webdigi** [comment]
Added mapping for the new London region. See https://github.com/webdigi/AWS-VPN-Server-Setup/commit/b11ecc374593790433d2a659d45d7be7e9856a1a
