### ISSUE TITLE
L2TP not working and when ec2 machine restarts, it doesn't work

### ISSUE THREAD

**Issue by hsb1007** [webdigi/AWS-VPN-Server-Setup#26]
Hi, as soon as the Cloud formation is created, it works fine with PPTP but not with L2TP.

It connects successfully but it can not browse to any site.

Also I have tried to set up with Elastic Ip , which worked great (with PPTP) but if I stop the instance and start again, it connects but again it doesn't resolve to any site.

Do you have any idea why and how we can fix this?

**Comment by webdigi** [comment]
Most users mentioned that you will have to wait for approx 5 minutes after reboot to connect. Please reopen if you still have an issue.
