### ISSUE TITLE
Create UK region template

### ISSUE THREAD

**Issue by downtownwillbrown** [webdigi/AWS-VPN-Server-Setup#28]
Any chance of developing a template for the newly released UKAWS region?
Thanks

**Comment by webdigi** [comment]
This was in the recent update? Did you manage to try it with the UK AWS region?

**Comment by downtownwillbrown** [comment]
Apologies, I saw no update on the blog so didn’t try. Please ignore my lazy request

William Brown
+44 7585 304 369
+33 7 81 59 18 43

**Comment by webdigi** [comment]
No problem.
