### ISSUE TITLE
L2TP does not persist for Apple iOS VPN

### ISSUE THREAD

**Issue by ghost** [webdigi/AWS-VPN-Server-Setup#29]
Love the article, and really appreciate the fact that you've provided updates to it as things have changed (i.e., loss of support for PPTP from Apple iOS). 

I have set up L2TP VPN for a few Apple devices. It works great when connected, but the VPN connections do not persist - meaning: if I set my iPhone aside for a while, the VPN drops and I have to reconnect it manually when I go to use the iPhone again. 

The upside is that it makes me pay close attention to my VPN icon at the top of the screen, so my situational awareness is high, but the downside is, "what if I forget?". 

Any ideas on implementing workarounds for persistence that won't be complete resource hogs?

**Comment by webdigi** [comment]
Can you please let me know what region you use? I am not sure if this is something region or network specific as others have not reported this.

**Comment by jrgarrigues** [comment]
Sorry @webdigi, missed your note. I'm on US East (N. Virginia). I've rebuilt the stack a couple times to see if it was a fluke, but I get the same results every time (meaning, the connection to the VPN drops pretty quickly and I have to re-connect a lot). I get the attached message on my iOS devices after the connection drops... 

![img_0994](https://cloud.githubusercontent.com/assets/23805961/24025558/933100c0-0a91-11e7-9887-85c62bfb87d7.jpg)

**Comment by y3sh** [comment]
I had this issue as well for the first time that I created a cloud formation.  I solved it by deleting the first cloud formation and re-adding another.  So far so good...  The VPN server seems to be accepting connections 24 hours later.

**Comment by y3sh** [comment]
Also note that I used a different region (Ohio).

**Comment by victorbordo** [comment]
This may be a region specific issue. US-East 1 (N. Virginia) is the oldest 
AWS infrastructure in place. I've heard that certain oddities occurring in that region can be attributed to age. Just a hunch

**Comment by webdigi** [comment]
We have a major update to the VPN server code and this should improve stability significantly. I look forward to your tests on the new system 333b293

Please do follow instructions https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/ or video https://www.youtube.com/watch?v=fBBERp5CUgo and let us know if you have any trouble with the new system.

@y3sh @ghost @victorbordo @flipy - Please do reopen if you still have issues.
