### ISSUE TITLE
Not forwarding traffic, IP unchanged on Mac OS X

### ISSUE THREAD

**Issue by emkman** [webdigi/AWS-VPN-Server-Setup#30]
I used the latest JSON template with Key Pair name from this repo, and the instance started fine. I connected over L2TP from OS X 10.11.6 and it connects succesfully, however my traffic doesn't seem to be routing through my VPN instance. Both my browser and my command line continue to report my original IP address, not the IP of my EC2 instance. I also cannot access my ElasticCache redis cluster behind our VPC, which I could access with OpenVPN. Are there more configuration settings needed either on my desktop or on the server?

**Comment by webdigi** [comment]
did you miss this step  https://www.webdigi.co.uk/blog/wp-content/uploads/2015/03/MAC-VPN-Step6.png

you have to send all traffic through the VPN.

**Comment by emkman** [comment]
Yes, I did. I was looking all over for a setting like that and somehow didn't see it right in front of me. I also was able to connect to my ElasticCache cluster after adding the default VPC security group to the VPN instance. Thanks!!
