### ISSUE TITLE
Cannot connect to Mumbai server over L2TP(IPSec)

### ISSUE THREAD

**Issue by mohitathwani** [webdigi/AWS-VPN-Server-Setup#31]
I just set up my EC2 instance with your json template and tried to connect my Mac and iPhone and I get the message:

`The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.
`

**Comment by webdigi** [comment]
We have a major update to the VPN server code and this should improve stability significantly. I look forward to your tests on the new system 333b293

Please do follow instructions https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/ or video https://www.youtube.com/watch?v=fBBERp5CUgo and let us know if you have any trouble with the new system.

@mohitathwani - Please do try and let us know if you still have trouble

**Comment by mohitathwani** [comment]
No luck even with the new update!

**Comment by webdigi** [comment]
Thanks for testing. Most users have reported that it has worked for them. 

Can you please let me know if you tried to connect to the VPN server on a office network / home network?
