### ISSUE TITLE
VPN Issues N Virginia and N California  - L2TP - Mac

### ISSUE THREAD

**Issue by mattmelwoll** [webdigi/AWS-VPN-Server-Setup#32]
Hey just wanted to say thank you for posting this, when I first set it up originally about 2 months ago was working beautifully.

When I originally set it up I used the N Virginia region and everything was working fine with no issues.

Just recently when trying to use the VPN I keep getting the following error message:

_The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator._

I decided to create another stack using the N California region and it work perfectly for about 20 minutes then I was booted off with the same error message and I couldn't reconnect.

not sure if anyone else has encountered this?

**Comment by webdigi** [comment]
So your N Virginia and N California does not work at the moment?

**Comment by petoskey** [comment]
@webdigi - When creating a new CloudFormation stack in N.Virginia, the create process fails due to this error -

> The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.

Thanks for your help

**Comment by webdigi** [comment]
@petoskey - It looks like your default VPC is deleted. 

Can you please try another region or alternatively just create a new support ticket to AWS and tell them to "Please restore my default VPC for the region N.Virginia". That should then help you with the setup.

**Comment by mattmelwoll** [comment]
Hi @webdigi yes that is correct I haven't been able to get those VPNs working.

**Comment by dinofifa** [comment]
Mine has the same issue too. I've been used VPN @ Oregon region for the past 6 months...everything works fine until last week. I tried to create another stack with same instruction and got the same error message :-(

**Comment by webdigi** [comment]
We have a major update to the VPN server code and this should improve stability significantly. I look forward to your tests on the new system https://github.com/webdigi/AWS-VPN-Server-Setup/commit/333b293a1aa19b03dae0023f2d18ebf023717181

Please do follow instructions https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/ or video https://www.youtube.com/watch?v=fBBERp5CUgo and let us know if you have any trouble with the new system.

@dinofifa @mattmelwoll @petoskey - Please reopen if this does not work for you.

**Comment by dinofifa** [comment]
It works! Thanks :-)

**Comment by webdigi** [comment]
@dinofifa thanks for testing the updated version!
