### ISSUE TITLE
DNS Probe Error on Linux over PPTP

### ISSUE THREAD

**Issue by theasianpianist** [webdigi/AWS-VPN-Server-Setup#33]
I'm dual-booting Ubuntu and Windows 10 on the same machine, and the VPN works when I connect to it from Windows. So I tried using the default template and connecting to the VPN in Linux (Ubuntu 17.04). After connecting to the VPN, every time I tried to load a website I'd get a bad DNS probe error in Chrome, and the page just wouldn't load in Firefox. Because I'm located in China, I thought it might have to do with the fact that China blocks Google servers, so I changed the DNS addresses in the template to use Open DNS, to no avail. 

I used Ubuntu's native network connection managers to create the VPN connection, using MPPE, stateful encryption, BSD compression, deflate compression, and TCP header compression. I've also tried manually inputting the Open VPN addresses into the Ubuntu VPN configuration manager, which didn't work either.

**Comment by webdigi** [comment]
@theasianpianist - please try again with the latest update.
