### ISSUE TITLE
Dynamic DNS Feature

### ISSUE THREAD

**Issue by zwavoo** [webdigi/AWS-VPN-Server-Setup#37]
It would be great to add a dynamic DNS function to the server, so I tried adding inadyn to the CF template, but I think I broke it. Is there already a feature to use Dynamic DNS installed or can you suggest the best point to add the "apt-get install inadyn" etc to the script?

I know that "broke it" isnt much help, but since I cant SSH into it, I cant retrieve any logs (another question I guess).

**Comment by webdigi** [comment]
Please try https://github.com/webdigi/AWS-VPN-Server-Setup/blob/master/src/output/Unified-Cloud-Formation.json change line 574 to
"apt-get install inadyn -y\n",
Let me know if that works for you.

**Comment by zwavoo** [comment]
I went a little further, by inserting the following at line 574...
                "apt-get install inadyn -y\n",
                "echo \"--username my@email.here\" > /etc/inadyn.conf\n",
                "echo \"--password xxxxxxxx \" >> /etc/inadyn.conf\n",
                "echo \"--alias abbeyfarm-vpn.ddns.net\" >> /etc/inadyn.conf\n",
                "echo \"--update_period_sec 600\" >> /etc/inadyn.conf\n",
                "echo \"--background\" >> /etc/inadyn.conf\n",
                "echo \"--dyndns_system default@no-ip.com\" >> /etc/inadyn.conf\n",
                "service inadyn restart\n",
What I can tell (as Ive added SSH, so can get in now) is that inadyn IS now installed, and appears to be running, but not actually updating the IP address. Any thoughts?

**Comment by zwavoo** [comment]
so I made a few extra additions on top of your suggestion. at line 574, I inserted:
                "apt-get install inadyn -y\n",
                "echo \"--username my@email.here\" > /etc/inadyn.conf\n",
                "echo \"--password xxxxxxxx \" >> /etc/inadyn.conf\n",
                "echo \"--alias aliasvpn.ddns.net\" >> /etc/inadyn.conf\n",
                "echo \"--update_period_sec 600\" >> /etc/inadyn.conf\n",
                "echo \"--background\" >> /etc/inadyn.conf\n",
                "echo \"--dyndns_system default@no-ip.com\" >> /etc/inadyn.conf\n",
                "service inadyn restart\n",
and although I see inadyn installed (I now have SSH installed too) and I think running, it never actually updates the DNS server. thoughts?

**Comment by webdigi** [comment]
There is another template which lets you SSH to the server with a keypair. See https://github.com/webdigi/AWS-VPN-Server-Setup/blob/master/src/output/Unified-Cloud-Formation-Key-Name.json and you can ssh to the server to find out what's wrong

**Comment by zwavoo** [comment]
yes thats all working now with your template. I had some issues with inadyn that required a few config file changes. for completeness, here are the added lines to the CF template that makes it all work :
                "apt-get install inadyn -y\n",
                "echo \"--username me@email.com\" > /etc/inadyn.conf\n",
                "echo \"--password xxxxx \" >> /etc/inadyn.conf\n",
                "echo \"--alias hostnamealias.ddns.net\" >> /etc/inadyn.conf\n",
                "echo \"--update_period_sec 600\" >> /etc/inadyn.conf\n",
                "echo \"--background\" >> /etc/inadyn.conf\n",
                "echo \"--dyndns_system default@no-ip.com\" >> /etc/inadyn.conf\n",
                "service inadyn stop\n",
                "sed 's/RUN_DAEMON=\"no\"/RUN_DAEMON=\"yes\"/g' /etc/default/inadyn > /etc/default/inadyn2\n",
                "mv /etc/default/inadyn2 /etc/default/inadyn\n",
                "systemctl enable inadyn.service\n",
                "systemctl start inadyn.service\n",
Thanks again for a fantastic application.

**Comment by webdigi** [comment]
Awesome! Thanks.
