### ISSUE TITLE
Requires VPC

### ISSUE THREAD

**Issue by jethroguce** [webdigi/AWS-VPN-Server-Setup#4]
I have issues with the stack it requires to have the EC2 instance built inside a VPC but the template doesn't ask for the VPC or creates one.

![screen shot 2015-06-24 at 10 14 53 am](https://cloud.githubusercontent.com/assets/4945428/8321485/fa6196f8-1a59-11e5-9995-1591df48bf79.png)

**Comment by webdigi** [comment]
The stack uses the default VPC. Did you delete your default VPC? You can also try another region and see if it will work.

**Comment by jethroguce** [comment]
I see, yes I have deleted the default VPC, thanks.

**Comment by webdigi** [comment]
Please try another region as the stack can only access the default VPC. Alternatively, you could contact amazon support and get them to restore your default VPC.
