### ISSUE TITLE
Ultra is an unsupported configuration in US East (Ohio)

### ISSUE THREAD

**Issue by stewartbryson** [webdigi/AWS-VPN-Server-Setup#40]
When using the template that's hosted on S3 bucket `https://s3.amazonaws.com/webdigi/VPN/Unified-Cloud-Formation.json`, the CloudFormation stack fails with "unsupported configuration".

**Comment by webdigi** [comment]
can you please try another region and reopen if you still have an issue

**Comment by stewartbryson** [comment]
`m3.xlarge` does not exist in Ohio. Changing to `m4.xlarge` fixes this.

**Comment by webdigi** [comment]
thanks. that helps to identify the problem!
