### ISSUE TITLE
Cloud formation stack not working

### ISSUE THREAD

**Issue by mabbas007** [webdigi/AWS-VPN-Server-Setup#41]
Using the template file with cloud formation, I'm trying to connect to the output server but it doesn't respond at all

**Comment by webdigi** [comment]
what region did you try? can you try another region? Also, please do try another device.

Any errors while creating the stack?

**Comment by mabbas007** [comment]
I've used London region, I'll try to change it

**Comment by mabbas007** [comment]
I've changed to N.Virginia but not working as well

**Comment by webdigi** [comment]
please do try another device.

Any errors while creating the stack?

**Comment by mabbas007** [comment]
Yeah, I've tried it from my mac and android device but the same results, not responding.

**Comment by mabbas007** [comment]
No errors while creating the stack 
`	10:49:24 UTC+0200	CREATE_COMPLETE	AWS::CloudFormation::Stack	test-VPN	
10:49:22 UTC+0200	CREATE_COMPLETE	AWS::EC2::Instance	VPNServerInstance	
10:48:49 UTC+0200	CREATE_IN_PROGRESS	AWS::EC2::Instance	VPNServerInstance	Resource creation Initiated
10:48:48 UTC+0200	CREATE_IN_PROGRESS	AWS::EC2::Instance	VPNServerInstance	
10:48:44 UTC+0200	CREATE_COMPLETE	AWS::EC2::SecurityGroup	VPNSecurityGroup	
10:48:44 UTC+0200	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	VPNSecurityGroup	Resource creation Initiated
10:48:41 UTC+0200	CREATE_IN_PROGRESS	AWS::EC2::SecurityGroup	VPNSecurityGroup	
10:48:36 UTC+0200	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	test-VPN	User Initiated`

**Comment by webdigi** [comment]
thanks. what is the error on mac and android

**Comment by mabbas007** [comment]
This the message I get on mac
The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

On android just says not connected

**Comment by webdigi** [comment]
did you make any changes to the script? also did you set shared key correctly. finally can you please try from a different network also. probably a data network on your android device?

**Comment by mabbas007** [comment]
No I didn't make changes to the script, I've entered the shared key correctly.
I will try a different network, I' sorry for the trouble

**Comment by mabbas007** [comment]
Well it worked on my data connection, I think my ISP is blocking my VPN connection !!.

**Comment by mabbas007** [comment]
So my last question would be, is there a way to use OpenVPN with AWS ?

**Comment by webdigi** [comment]
thanks for confirming issue with network provider. sorry we only support l2tp and PPTP. openvpn is possible with AWS but not setup by us.
