### ISSUE TITLE
Can we use multiple account on it?

### ISSUE THREAD

**Issue by kangdenglin** [webdigi/AWS-VPN-Server-Setup#42]
It seems that I can only set single VPN connection account on it. Is there any way to set up more account? And I do not know the ubuntu system account's password....

**Comment by webdigi** [comment]
you can use the same user account for multiple connections at the same time. You can add multiple users but you will have to edit the script yourself.

If you need to access the server you need to use https://github.com/webdigi/AWS-VPN-Server-Setup/blob/master/src/output/Unified-Cloud-Formation-Key-Name.json (not for newbies)
