### ISSUE TITLE
Doesn't work and an interesting email from AWS a couple of days after the try

### ISSUE THREAD

**Issue by whynotthough** [webdigi/AWS-VPN-Server-Setup#47]
Does anybody know why I got an email notification from AWS about activating of DynamoDB a couple days after I unsuccessfully tried this instruction?.......

**Comment by webdigi** [comment]
Dynamodb is not used with this service so it should not be related.

Was there any error when trying to create the stack? Also what was the error when trying to connect? Did you also try creating in another region?
