### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by mparekhaspl** [webdigi/AWS-VPN-Server-Setup#51]
Hi - Is IP address assigned by cloud formation stack elastic IP? If not, would it change on instance restart? Thank you.

**Comment by webdigi** [comment]
Elastic IP is not assigned now. So yes it will change in restart. You can easily assign elastic IP to your instance from the AWS control panel and then connect to your instance using it. 

Note elastic ips are charged when instance is stopped.
