### ISSUE TITLE
Does not work with Lono 4

### ISSUE THREAD

**Issue by alukach** [webdigi/AWS-VPN-Server-Setup#53]
Similar to #48, this codebase does not appear to work with Lono 4:

```sh
▶ lono generate
Generating CloudFormation templates, parameters, and scripts
ERROR: The config/settings.yml does not exist in this project.  Are you sure you are in lono project?

▶ lono --version
4.0.6
```

Should we pin the version to the last version of Lono 3.x (3.5.0) or it may also be simple to upgrade this module to work with Lono 4 via the [`lono upgrade4`](https://github.com/tongueroo/lono/blob/a3808d50630aabafe3e38ad1f40f56035a2f6c2a/CHANGELOG.md#400) command.  I know very little about Lono or Ruby so I'm hesitant to try to fix it myself.

**Comment by webdigi** [comment]
Thanks for reporting. Please try lono version 3.3.2 or some 3.x version and it should work. Please reopen the issue if it does not work.

Also, yes if lono upgrade works then please send a pull request or an update. Happy to use the latest lono if someone confirms it works.
