### ISSUE TITLE
VPN is unstable

### ISSUE THREAD

**Issue by carlostrianag** [webdigi/AWS-VPN-Server-Setup#55]
I have followed the steps on the video and it worked perfectly! Just wondering is it ok that the VPN drops the connection after a random amount of time?

I have also made a connection with my VPN server via SSH, and added 2 extra usernames and passwords. After this, VPN started to present instability, but it would get worst when 3 of us were connected at the same time. Does this have been designed for just one user? Or could maybe this is a known issue?

Thanks in advance for any help you can provide.

**Comment by rosoposo** [comment]
What size server did you provision? It should work for multiple users.

**Comment by webdigi** [comment]
What size server did you provision? It should work for multiple users.

**Comment by carlostrianag** [comment]
Hi, thanks for the quick response.

First time I launched it, I have used a t2.micro instance. Started to realize it was not working as expected, so I have used a t2.medium instance after that, but it made no difference.

**Comment by webdigi** [comment]
Let us know if you confirm it is caused by multiple users accessing at the same time. Will check this further

**Comment by carlostrianag** [comment]
I'm sorry for the delay on responding. I have downloaded the new .yaml file and set up a new CloudFormation in a different region this time (Ohio), I will let you know how it goes. Gonna try tomorrow with 3 or 4 users.

**Comment by webdigi** [comment]
Please try and use this new update https://github.com/webdigi/AWS-VPN-Server-Setup/blob/668fb6eb9a01cc69966df793f148facf6e2e3b2d/Unified-Cloud-Formation.yaml
