### ISSUE TITLE
Router VPN Configuration

### ISSUE THREAD

**Issue by diegoguidobono** [webdigi/AWS-VPN-Server-Setup#6]
Hi, I'm trying to configure a [TL-ER604W](http://www.tp-link.com/resources/document/TL-ER604W_V1_User_Guide_19100.pdf) but can't find which is the remote subnet configured in the template.

**Comment by webdigi** [comment]
Did you manage to find VPN config? It will be useful to add it to the docs https://github.com/webdigi/AWS-VPN-Server-Setup/tree/master/docs
