### ISSUE TITLE
VPC Required for Instance Type

### ISSUE THREAD

**Issue by digiance** [webdigi/AWS-VPN-Server-Setup#60]
Receiving this error on all instance types:

The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (Service: AmazonEC2; Status Code: 400; Error Code: VPCResourceNotSpecified; Request ID: f92f924b-6c5a-477b-857f-c992fcbbcc74)
--

**Comment by webdigi** [comment]
Did you delete your default vpc? Also please try another region

**Comment by digiance** [comment]
Used Ohio region and this fixed the issue.
