### ISSUE TITLE
Solution to Pause a stack

### ISSUE THREAD

**Issue by machinefriendly** [webdigi/AWS-VPN-Server-Setup#62]
Is it possible to have a stack to be paused instead of be deleted? Given I use a VPN only several days per year, but it costs me all the days ( around 0.4$/day ). 
I Googled and find that it requires modification on template and I'm not sure it's secured so I ask here for a solution.
Thanks in advance,

**Comment by webdigi** [comment]
easiest solution is to browse to instances and stop the instance. start it later when you want.

there is no pause available in cloudformation stack.
