### ISSUE TITLE
can not ping the CGW 

### ISSUE THREAD

**Issue by ArnoHK** [webdigi/AWS-VPN-Server-Setup#64]
We set up the VPN 2 weeks ago and it was working well. Very easy to set up. We came back from holidays and it is not working anymore. 
I have updated the password to re-activate the service. But still not working. 
We can not ping the CGW : 52.221.184.6
We configure the Asus router and also the Macbook with L2TP.  Both can not connect. 
On macbook is written : "The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator."

Any idea ?

**Comment by webdigi** [comment]
Is the instance still running? You might have to delete stack and create it again? Not sure why it would stop working.

**Comment by ArnoHK** [comment]
Yes the instance is still working. 
Ok I will try to create the stack again.

**Comment by ArnoHK** [comment]
It works, Thanks !

**Comment by ArnoHK** [comment]
I will monitore it. I close it anyway. Thanks for your immediate answer.
