### ISSUE TITLE
The PPTP-VPN server did not respond.

### ISSUE THREAD

**Issue by tanyanghan** [webdigi/AWS-VPN-Server-Setup#7]
I keep getting this error when trying to connect on the Mac:

The PPTP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

I also cannot connect on my Nexus 5X phone.

I am able to ping the instance, as well as log in via SSH. Just cannot connect to the VPN. Any pointers how to debug this?

**Comment by webdigi** [comment]
you will not be able to login via SSH. not sure how you managed to do that? are you sure you created the instance with the template?

**Comment by tanyanghan** [comment]
I added a few things to the json file.

I needed to be in Seoul:
`      "ap-northeast-2": {
        "HVM64": "ami-54ae603a"
      },`

Entered a new parameter for the KeyPair KeyName:
`    "KeyName": {
      "Description": "Name of an existing EC2 KeyPair to enable SSH access to the instance",
      "Type": "AWS::EC2::KeyPair::KeyName",
      "ConstraintDescription": "must be the name of an existing EC2 KeyPair."
    }`

Added a couple security group:
`          {
            "CidrIp": "0.0.0.0/0",
            "FromPort": "8",
            "IpProtocol": "icmp",
            "ToPort": "-1"
          },
          {
            "CidrIp": "0.0.0.0/0",
            "FromPort": "22",
            "IpProtocol": "tcp",
            "ToPort": "22"
          }`

Added the above KeyName parameter to the Instance Properties:
`    "VPNServerInstance": {
      "Properties": {
        "KeyName" : { "Ref" : "KeyName" },
        "ImageId": {`

**Comment by webdigi** [comment]
Please wait upto 10 minutes after setting up the instance to make sure that the VPN is active. Also try a few different regions also. Also try just the base template and see if that works, this is to make sure that above changes do not cause a problem.

**Comment by tanyanghan** [comment]
I finally got connected. It turned out to be a password problem. I generated a super secure password with 1password (40 characters, with numbers and symbols) and I couldn't log in. Then I tried a much simpler password - 16 characters with numbers only and now I am able to connect to the VPN. I guess it's the symbols?

**Comment by webdigi** [comment]
thanks. that should be the problem then. Do you know if the password had @ or quotes?

**Comment by tanyanghan** [comment]
Yes, it had a couple @'s in it. :lol: No quotes. Do you know what are the accepted characters for the password?

**Comment by LittleBird-Western** [comment]
Thank you for this. I had a complex password also (containing a # and a !) and it would not allow me to connect.

**Comment by webdigi** [comment]
@LittleBird-Western - thanks for the comment. We will have a look with passwords containing those special characters.
