### ISSUE TITLE
How to add support for a new zone?

### ISSUE THREAD

**Issue by jmgibbons1** [webdigi/AWS-VPN-Server-Setup#71]
I'm looking at setting up a VPN server in Bahrain me-south-1. 

I can modify the cloudformation template but where do I get the HVM64 ami mapping for this region?

Thank you.

**Comment by MRZ-OW** [comment]
that is exactly what i am trying to do, did you manage to figure this out?? i tried so much

**Comment by shadowsaw** [comment]
[VPN-updated.zip](https://github.com/webdigi/AWS-VPN-Server-Setup/files/3687560/VPN-updated.zip)

**Comment by webdigi** [comment]
very easy to add a new zone. all you have to do is fine the correct AMI for the region. Take any Ubuntu 18.04 or Ubuntu 16.04 and do this https://github.com/webdigi/AWS-VPN-Server-Setup/commit/97fc64b84918cafb822861bfb95300e72975591c
