### ISSUE TITLE
Unable to create VPN in Bahrain Zone

### ISSUE THREAD

**Issue by inaamiub** [webdigi/AWS-VPN-Server-Setup#74]
I tried creating a VPN in Bahrain Zone but couldn't succeed. I got the following output
![image](https://user-images.githubusercontent.com/16742248/69611371-13da0880-1047-11ea-9125-b4bc6ba1d995.png)

**Comment by webdigi** [comment]
Can you please try with https://webdigi.s3.amazonaws.com/VPN/Unified-Cloud-Formation.yaml and reopen this if that does not work.
