### ISSUE TITLE
Not able to connect to internet

### ISSUE THREAD

**Issue by nSpider** [webdigi/AWS-VPN-Server-Setup#76]
I have used this method previously, but now I am unable to connect to the internet while connected to the VPN.

**Comment by abishak2020** [comment]
I am unable to connect to the internet while connected to the VPN.

**Comment by nSpider** [comment]
I tried different things but in vain. It works from my mobile device but it does not work with my laptop. OS: Windows 10

**Comment by nSpider** [comment]
Solved the problem using the following guide. https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809
