### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by cevatkerim** [webdigi/AWS-VPN-Server-Setup#8]
I tried PPTP as well as IPSEC. Either way it won't connect. Redeploying/rebooting the server does not help either. I tried it on both mac and ios.

**Comment by webdigi** [comment]
What region did you try? Were you able to connect to it say via the phone network? 

We have reports of certain users not being able to connect to VPN from universities or certain networks that block VPNs.

**Comment by webdigi** [comment]
Please reopen if you have more info
