### ISSUE TITLE
PPTP works but L2TP/IPSec does not connect

### ISSUE THREAD

**Issue by xiaohanzhu** [webdigi/AWS-VPN-Server-Setup#9]
After setup the cloud formation.  I was able to successfully connect to the VPN server with pptp protocol.  However when trying to use L2TP/IPsec with presharedkey.  Windows VPN keeps on giving errors on can not establish connections with the server

**Comment by webdigi** [comment]
Can you please try a phone or another device that supports L2TP/IPSEC? just to be sure that it is not the windows connection issue

**Comment by xiaohanzhu** [comment]
I have tried both android and windows.  The complaints on windows were “the connection to the remote computer could not be established, so the port used for this connection was closed”

On Android is was similar failure on connection.

**Comment by webdigi** [comment]
So you are sure that L2TP/IPSEC you have used the correct username and password, passpharse but does not connect. This works fine in my tests with the latest server also.

Can you please create another one also for a test in another region. It is highly unlikely as it works fine on our latest test and it was not reported by any other user.

**Comment by xiaohanzhu** [comment]
I tried both Singapore region and US Oregon.  Here are the credentials for one of the servers:

52.38.37.133

Shared Key: jdvpn

User name: jdcapital

Password: JDCapital123!

**Comment by Tinky** [comment]
Hi Webdigi, This seems to be the "sha_truncbug" issue. This is an issue for most android devices. I couldn't work out how to use a different sha algorithm but adding sha_truncbug=yes to the /etc/ipsec.conf file resolved this issue for me.
https://code.google.com/p/android/issues/detail?id=196939#c202

**Comment by webdigi** [comment]
@Tinky - Thanks for that. Please submit a pull request if possible. 

We will also have to test this with mac & pc's to be sure they work.

**Comment by Tinky** [comment]
@webdigi Sorry, I don't know how to git. I also had a typo above. 
The fix is to add " sha2_truncbug=yes" to the /etc/ipsec.conf file.
I've been able to reproduce this issue on a samsung tab a 8 and a nexus 9 both running android 6.

**Comment by webdigi** [comment]
@Tinky - do you know if this still works on ok a Mac / PC?

**Comment by webdigi** [comment]
We have a major update to the VPN server code and this should improve stability significantly. I look forward to your tests on the new system 333b293

Please do follow instructions https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/ or video https://www.youtube.com/watch?v=fBBERp5CUgo and let us know if you have any trouble with the new system.

@Tinky @xiaohanzhu - The latest update should work well and be stable enough. Please do try and let us know.
